data:
  adversarial_attacks: [
    # "ONE_PIXEL",
    "FGSM",
    "FGSM",
    # "PGD",
    # "FAB",
    # TODO: add remaining attacks
  ]
  seed: 42
  use_rir: False
  use_bg: False
  use_lowpass: False

  noise_path: "custom_data/combined/*.wav"

  sample_rate: 16_000
  duration: 5

checkpoint:
  # This part is used only in evaluation (each checkpoint is used in eval on corresponding fold).
  # To ensure reliable results make sure that the order of checkpoints is correct (i.e. fold_0, fold_1, fold_2)
  path: ""

model:
  name: "lcnn"
  parameters:
    input_channels: 1
    frontend_algorithm: ["mfcc"]
    output_dim: 2
  optimizer:
    lr: 0.0001
  loss:
    name: "focal"
    # name: "bce"
    fake_weight: 0.7
    alpha: 0.25
    sam: True
    weight_decay: 1e-4
    scheduler: True

logging:
  log_metrics: True
  existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
  name: "Initial adversarial training"
  description: ""
  tags: ["adversarial_training"]
